name = "bdf-f"
version = "0.2.20230618"
license = "MIT"
author = "ZUO Zhihua"
maintainer = "ZUO Zhihua (zuo.zhihua@qq.com)"
copyright = "Copyright 2019~2023, ZUO Zhihua"
categories = ["Patran", "BDF", "mesh", "CAE"]

[build]
auto-tests = true
auto-examples = true

[preprocess]
[preprocess.cpp]
macros = ["FPM"]

[dev-dependencies]
test-drive = { git='https://gitee.com/fortran-base/test-drive', tag='v0.4.0' }
