name = "bdf-parser"
version = "0.1.3"
license = "MIT"
author = "左志华"
maintainer = "左志华(zuo.zhihua@qq.com)"
copyright = "Copyright 2022, 左志华"
categories = ["Patran", "BDF", "mesh", "CAE"]

[build]
auto-tests = true
auto-examples = true
