name = "bdf-parser"
version = "0.1.1"
license = "MIT"
author = "左志华"
maintainer = "左志华(zuo.zhihua@qq.com)"
copyright = "Copyright 2022, 左志华"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false
